version: 0.0
os: linux
files:
  - source: dist/MyAngularProject
    destination: /var/www/MyAngularProject
permissions:
  - object: /var/www/MyAngularProject
    pattern: '**'
    mode: '0755'
    owner: root
    group: root
    type:
      - file
      - directory
