version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true
permissions:
  - object: /var/www/html
    pattern: '**'
    mode: '0755'
    owner: ec2-user
    group: ec2-user
    type:
      - file
      - directory
